package sport.app.sport_connecting_people.event;

public enum RequestEventType {

    FRIENDSHIP_REQUEST, FRIENDSHIP_REQUEST_ACCEPT, FRIENDSHIP_REQUEST_DECLINE,
    EVENT_INVITATION_REQUEST, EVENT_INVITATION_REQUEST_ACCEPT, EVENT_INVITATION_REQUEST_DECLINE,
    CANCEL_REQUEST
}
